### ISSUE TITLE
Broken for Python 3

### ISSUE THREAD

**Issue by christianbrodbeck** [conda-forge/apptools-feedstock#7]
Apptools from conda-forge seems to be broken for Python 3 (see error below), and the failing import  is in current master. However, apptools works if installed from `pip`, which makes me wonder whether there is some packaging magic or `future`-like module that needs to be applied?

```
$ conda create -n test -c conda-forge apptools python=3.6
Solving environment: done

## Package Plan ##

  environment location: /anaconda3/envs/test

  added / updated specs: 
    - apptools
    - python=3.6


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    wheel-0.31.1               |           py36_0          62 KB  conda-forge
    libpng-1.6.35              |       ha92aebf_0         321 KB  conda-forge
    icu-58.2                   |       hfc679d8_0        22.8 MB  conda-forge
    six-1.11.0                 |           py36_1          20 KB  conda-forge
    pip-9.0.3                  |           py36_0         1.7 MB  conda-forge
    pyqt-5.6.0                 |   py36h8210e8a_6         4.2 MB  conda-forge
    setuptools-40.0.0          |           py36_0         550 KB  conda-forge
    certifi-2018.4.16          |           py36_0         142 KB  conda-forge
    sip-4.18                   |           py36_1         245 KB  conda-forge
    traits-4.6.0               |   py36h470a237_2         409 KB  conda-forge
    apptools-4.4.0             |             py_1         200 KB  conda-forge
    qt-5.6.2                   |       h9e3eb04_4        65.4 MB  conda-forge
    pygments-2.2.0             |             py_1         622 KB  conda-forge
    jpeg-9c                    |       h470a237_0         246 KB  conda-forge
    python-3.6.5               |                1        13.9 MB  conda-forge
    ------------------------------------------------------------
                                           Total:       110.8 MB

The following NEW packages will be INSTALLED:

    apptools:        4.4.0-py_1           conda-forge
    ca-certificates: 2018.4.16-0          conda-forge
    certifi:         2018.4.16-py36_0     conda-forge
    configobj:       5.0.6-py36_0                    
    icu:             58.2-hfc679d8_0      conda-forge
    jpeg:            9c-h470a237_0        conda-forge
    libpng:          1.6.35-ha92aebf_0    conda-forge
    ncurses:         5.9-10               conda-forge
    openssl:         1.0.2o-0             conda-forge
    pip:             9.0.3-py36_0         conda-forge
    pyface:          6.0.0-py_1           conda-forge
    pygments:        2.2.0-py_1           conda-forge
    pyqt:            5.6.0-py36h8210e8a_6 conda-forge
    python:          3.6.5-1              conda-forge
    qt:              5.6.2-h9e3eb04_4     conda-forge
    readline:        7.0-0                conda-forge
    setuptools:      40.0.0-py36_0        conda-forge
    sip:             4.18-py36_1          conda-forge
    six:             1.11.0-py36_1        conda-forge
    sqlite:          3.20.1-2             conda-forge
    tk:              8.6.7-0              conda-forge
    traits:          4.6.0-py36h470a237_2 conda-forge
    traitsui:        6.0.0-py_1           conda-forge
    wheel:           0.31.1-py36_0        conda-forge
    xz:              5.2.3-0              conda-forge
    zlib:            1.2.11-h470a237_3    conda-forge

Proceed ([y]/n)? y


Downloading and Extracting Packages
wheel-0.31.1         |   62 KB | ##################################################################### | 100% 
libpng-1.6.35        |  321 KB | ##################################################################### | 100% 
icu-58.2             | 22.8 MB | ##################################################################### | 100% 
six-1.11.0           |   20 KB | ##################################################################### | 100% 
pip-9.0.3            |  1.7 MB | ##################################################################### | 100% 
pyqt-5.6.0           |  4.2 MB | ##################################################################### | 100% 
setuptools-40.0.0    |  550 KB | ##################################################################### | 100% 
certifi-2018.4.16    |  142 KB | ##################################################################### | 100% 
sip-4.18             |  245 KB | ##################################################################### | 100% 
traits-4.6.0         |  409 KB | ##################################################################### | 100% 
apptools-4.4.0       |  200 KB | ##################################################################### | 100% 
qt-5.6.2             | 65.4 MB | ##################################################################### | 100% 
pygments-2.2.0       |  622 KB | ##################################################################### | 100% 
jpeg-9c              |  246 KB | ##################################################################### | 100% 
python-3.6.5         | 13.9 MB | ##################################################################### | 100% 
Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate test
#
# To deactivate an active environment, use
#
#     $ conda deactivate

ISRWKAVW2269F ~$ conda activate test
(test) ISRWKAVW2269F ~$ python
Python 3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:44:09) 
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import apptools.scripting.recorder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/anaconda3/envs/test/lib/python3.6/site-packages/apptools/scripting/recorder.py", line 15, in <module>
    import __builtin__
ModuleNotFoundError: No module named '__builtin__'
```

**Comment by grlee77** [comment]
Thanks for reporting this.  It looks like appveyor uses `2to3` so we will need to roll back the `noarch` changes from #6. I can make a PR for that.
